### ISSUE TITLE
Support default.nix too

### ISSUE THREAD

**Issue by ryantm** [utdemir/nix-tree#10]
Flakes is an experimental feature, so it would be nice to also support standard features.

https://github.com/edolstra/flake-compat is an easy way to do that.

**Comment by utdemir** [comment]
Thanks for the issue. Sure, I added `default.nix` and `shell.nix` files using `flake-compat` with https://github.com/utdemir/nix-tree/commit/18d3443047c9da0b7d0f2d88115b29ca576ffc07.

My aim was `nix-tree` to be available on nixpkgs (it is), so the flake stuff was only for me to use when developing. But of course, having `flake-compat` doesn't hurt! Let me know if it now works for you.

**Comment by ryantm** [comment]
Oh, I used to be fetching this via niv, but I can switch to nixpkgs. Thanks!
