### ISSUE TITLE
Unrecognised flag '--derivation' on Nix 2.3.10

### ISSUE THREAD

**Issue by evanrelf** [utdemir/nix-tree#12]
The latest stable release of Nix doesn't recognize the `--derivation` option passed to `path-info`. I assume this is only available in Nix 3.0?

```
$ nix-tree $(nix-instantiate --expr "let pkgs = import <nixpkgs> {}; in pkgs.hello")
warning: you did not specify '--add-root'; the result might be removed by the garbage collector
error: unrecognised flag '--derivation'
Try 'nix --help' for more information.
nix-tree: Received ExitFailure 1 when running
Raw command: nix path-info --recursive --json --derivation /nix/store/ivs7c8av0mpy3j6mwdd7z7gikips17m2-hello-2.10.drv

$ nix --version
nix (Nix) 2.3.10
```

**Comment by utdemir** [comment]
Oh, this is annoying; sorry about that! I am on `nix (Nix) 2.4pre20201201_5a6ddb3` (`nixUnstable` from `nixpkgs-unstable` channel), and I just assumed that it would be there on stable Nix too.

I'll try the stable Nix version over the weekend to try to figure out a workaround. I hope there is a flag to do that which works on both stable and unstable version.

(By the way, the `--derivation` flag is only added when the store path ends with `.drv`, so you should still be able to use `nix-tree` for store paths).

**Comment by evanrelf** [comment]
No worries! 🙂 I was manually packaging the latest revision of `nix-tree`, but I don't have this issue after switching to the older version in Nixpkgs.

For whatever it's worth, I'm using `nix-tree` on `.drv` files and it _seems_ to work fine? So I'm not sure what the `--derivation` flag does. Maybe you're required to specify it explicitly in newer Nix versions?

If that's the case, you could just change which options you pass to `nix path-info` depending on the output of `nix --version`.

**Comment by utdemir** [comment]
> For whatever it's worth, I'm using nix-tree on .drv files and it seems to work fine? So I'm not sure what the --derivation flag does. Maybe you're required to specify it explicitly in newer Nix versions?

Oh, interesting. It looks like you are right, the behaviour of `nix path-info` is different across Nix versions:

```
% nix-shell -p nix --run 'nix path-info --json $(nix-instantiate --expr "let pkgs = import <nixpkgs> {}; in pkgs.hello") | jq -r .[0].path' 
/nix/store/zx648h10wgqjnr8skw5a7qcyxryjnilc-hello-2.10.drv

% nix-shell -p nixUnstable --run 'nix path-info --json $(nix-instantiate --expr "let pkgs = import <nixpkgs> {}; in pkgs.hello") | jq -r .[0].path'
/nix/store/8a6lbpbxbc5lc60ljwhw69sszr25ys5f-hello-2.10
% nix-shell -p nixUnstable --run 'nix path-info --derivation --json $(nix-instantiate --expr "let pkgs = import <nixpkgs> {}; in pkgs.hello") | jq -r .[0].path'
/nix/store/zx648h10wgqjnr8skw5a7qcyxryjnilc-hello-2.10.drv
```

In short; in stable Nix, when you pass a `.drv` to `path-info`, it returns information about the store derivation. However, when you do the same in `nixUnstable`, it "resolves' it and works on the output of given derivation; to actually work on the derivation you need to pass `--derivation`.

> If that's the case, you could just change which options you pass to nix path-info depending on the output of nix --version.

You are right, I think this is the way to go. I'll implement it these days. Thank you!

**Comment by evanrelf** [comment]
> In short; in stable Nix, when you pass a `.drv` to `path-info`, it returns information about the store derivation. However, when you do the same in `nixUnstable`, it "resolves" it and works on the output of given derivation; to actually work on the derivation you need to pass `--derivation`.

Interesting, I'll try and remember that for the future.

> You are right, I think this is the way to go. I'll implement it these days. Thank you!

Glad I could help! And thanks for making `nix-tree`, it has come in really handy at work!

**Comment by utdemir** [comment]
I just went ahead and implemented it. It now behaved as expected when I run it inside a nix-shell with `pkgs.nix`. Let me know if it doesn't for you, and thanks for the issue!

**Comment by evanrelf** [comment]
That fixed it for me; thanks! 🙂
