### ISSUE TITLE
Can not exit help window

### ISSUE THREAD

**Issue by EncodePanda** [utdemir/nix-tree#19]
# steps to reproduce

1. open nix-tree
2. type `?` to get help window
3. type `q` to exit the help window

*Expected:* help window(modal) is closed
*What actually happens:* Nothing happens

# relevenat source code
By studying the source code I found this https://github.com/utdemir/nix-tree/blob/main/src/App.hs#L287 so it seems that `q` should close the help window but it never does

**Comment by utdemir** [comment]
Thank you for the issue!

The line of code you found is spot on, and I think it _should_ fix this issue. This was a relatively [recent fix](https://github.com/utdemir/nix-tree/commit/1d334eb903c2ae380c2285a53ffb4db97255f1d0) released with `v0.1.4`. I can not reproduce the issue on the latest version.

That version hit `nixpkgs-unstable`, but not yet `nixpkgs-stable`. So my guess would be that you're using an older version. If this is the case, could you try using a version `>= 0.1.4`? If the issue persists, please let me know alongside with the version you have (`nix-tree --version`) and I'll take a look again.

**Comment by EncodePanda** [comment]
```
nix-tree --version
nix-tree 0.1.3.0
```

case closed :)
