### ISSUE TITLE
Cannot search for dependencies that have a 'q' in their name

### ISSUE THREAD

**Issue by piegamesde** [utdemir/nix-tree#21]
Because hitting 'q' closes the search mode ;)

**Comment by utdemir** [comment]
Yeah that was a funny bug :). But it should be fixed on version `1.2.0`, which is already at `nixpkgs-unstable`, however it's not in `nixpkgs-stable` yet.

Could you try updating your `nix-tree`?

**Comment by utdemir** [comment]
I'm going to close this issue because I _believe_ it is already fixed. Please do re-open it if you can reproduce it on newer versions.
