### ISSUE TITLE
Reverse dependencies (`--query --referrers`)

### ISSUE THREAD

**Issue by dschrempf** [utdemir/nix-tree#26]
Hi!

Thank you for developing this tool!

I was wondering if it is feasible to include a way to inspect reverse dependencies? Specifially, I was thinking about a way to add information obtained from `nix-store --query --referrers`. I need this command quite often, and it is very long (and hard to remember).

Thanks for you input!

Dominik

**Comment by KiaraGrouwstra** [comment]
looks like this can be done with `nix-store -q --referrers <store path>` (or `--referrers-closure`)
