### ISSUE TITLE
Feature request: inspect raw derivation

### ISSUE THREAD

**Issue by veprbl** [utdemir/nix-tree#30]
Would be very cool if nix-tree would allow to quickly view the selected derivation. Right now it can be done by switching to a different terminal to run `nix show-derivation` manually, but that's not so convenient.

**Comment by utdemir** [comment]
Thanks for the issue!

I think this is similar to: https://github.com/utdemir/nix-tree/issues/28

What do you think? If you agree, we can close this issue and continue the discussion there.

**Comment by veprbl** [comment]
It is similar. I've looked through the existing issues, but dismissed that one because of its title. Let's close.
