### ISSUE TITLE
how to change the order - e.g. alphabetical

### ISSUE THREAD

**Issue by InLaw** [utdemir/nix-tree#5]
is there a way to change the squence of listing in nix-tree 
- the size is default, but less helpfull if I would like to check for certain packages

**Comment by utdemir** [comment]
Yeah, `nix-tree` is currently mainly focused on investigating the disk usage. But I'll add a shortcut to change the sort order.

**Comment by utdemir** [comment]
I implemented this functionality on https://github.com/utdemir/nix-tree/commit/df01088741404fcfe4d9a7837fe52fa3a0b5dbeb (tl;dr: the key `s` toggles the order, and there are somes visual cues). Let me know what you think!
