### ISSUE TITLE
Unable to see the dependencies of pandoc flake

### ISSUE THREAD

**Issue by disbolog** [utdemir/nix-tree#58]
I am unable to use the tool with the pandoc development flake.

Here's the error message:
```shell
user@host ~/pandoc (main) [1]> nix-tree --derivation '.#'

error: attribute 'pandoc' missing

       at /nix/store/rw4gbrv5y2m59am2m1zc253hv1mbw1fs-source/flake.nix:42:28:

           41|         # Default package.
           42|         packages.default = self'.packages.pandoc;
             |                            ^
           43|
(use '--show-trace' to show detailed location information)
nix-tree: Received ExitFailure 1 when running
Raw command: nix path-info --json --derivation --extra-experimental-features "nix-command flakes" .#
```
Here's the `nix-info` output:
```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.26, NixOS, 23.05 (Stoat), 23.05.20230430.da45bf6`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `""`
 - nixpkgs: `not found`
 ``` 

And here are the steps to reproduce:
```shell
git clone https://github.com/jgm/pandoc
cd pandoc
nix-tree --derivation '.#'
```

To mention it, this is something I try in order to fix https://github.com/jgm/pandoc/issues/8818. There's also a nixpkgs update request for pandoc: https://github.com/NixOS/nixpkgs/issues/221165

**Comment by utdemir** [comment]
I think this is an issue on the pandocside, if the Nix evaluation errors out, there's nothing `nix-tree` can do.

I'm closing this issue, but please reopen it if the issue persist after the `pandoc`-side is fixed! :)
