### ISSUE TITLE
Support new path-info syntax introduced in nix 2.19

### ISSUE THREAD

**Issue by SuperSandro2000** [utdemir/nix-tree#67]
see https://nixos.org/manual/nix/stable/release-notes/rl-2.19 for details

Currently nix-tree fails with ``nix-tree: user error (Failed parsing nix path-info output.)``

**Comment by utdemir** [comment]
Pinned this issue for visibility. This is fixed on 0.3.2 however it hasn't dropped to any NixOS/nixpkgs releases yet (as of 29 Nov 2023).

In the meanwhile, one can use the overlay @SuperSandro2000 described here: https://github.com/utdemir/nix-tree/pull/68#issuecomment-1829766724

**Comment by utdemir** [comment]
Update: 0.3.2 is on `nixpkgs-unstable` so if you're following that branch you don't need to do anything. If not, you can pull from `nixpkgs-unstable` or use the workaround on above comment.
