### ISSUE TITLE
save to file - export - more than the window(tab) shows

### ISSUE THREAD

**Issue by InLaw** [utdemir/nix-tree#7]
Hello,
how can I export the whole hierarchy?

**Comment by utdemir** [comment]
You shouldn't even need `nix-tree` for that, something like:

```
nix-store -q --tree /var/run/current-system
```

can already give you the whole hierarchy. If you need it to be a bit more computer-readable, you can also look at `--dot` option of `nix-store`.

**Comment by InLaw** [comment]
thanks 

which --dot option?
- `nix-store -q --graph ~/.nix-profile | dot -Tps > graph.ps`

**Comment by utdemir** [comment]
> which --dot option?

Sorry, my mistake; it was `--graph` as you mentioned.
