### ISSUE TITLE
What does the color coding mean?

### ISSUE THREAD

**Issue by seanybaggins** [utdemir/nix-tree#77]
Some dependencies show up blue. What does the blue text mean?
![image](https://github.com/utdemir/nix-tree/assets/18423154/9f6bbb4f-e203-4586-bfe9-5cac04ca57ae)

**Comment by utdemir** [comment]
Right - that is not documented anywhere at all 😅 .

They are paths that do not have any dependencies. I don't remember why I made the effort to show them differently - probably to maybe convey that they are not worth scrolling to.
