### ISSUE TITLE
cursor disappears after exiting `nix-tree`

### ISSUE THREAD

**Issue by Atemu** [utdemir/nix-tree#88]
1. Open `nix-tree`
2. Press `q` to exit
3. Observe no more cursor in my shell

Reproduced using bash in mlterm and xterm.

```
nix-tree 0.4.0
```

https://github.com/Atemu/nixpkgs/commit/ae92c8291baa0f7ae78fff81706bcab7c962e4c2
https://github.com/Atemu/nixos-config/commit/8a269a5e4f47204ad1a1e2a0e18a2e471cc440d5

**Comment by utdemir** [comment]
Thanks @Atemu! Turns out it was because we weren't shutting down `vty` properly since `nix-tree-0.3.3`, I think. 

I fixed it with the commit above and released `v0.4.1`. Should drop into `nixpkgs` with the next `haskell-packages` update.

Let me know if you still have issues!

**Comment by Atemu** [comment]
Thanks for the quick fix, it appears to be working :)
